import type { InsertQuestion } from "@shared/schema";

export const sampleQuestions: InsertQuestion[] = [
  // ALGEBRA
  {
    subject: "Matematik", grade: "Åk 9", topic: "Algebra", type: "numeric",
    questionText: "Lös ekvationen: 3x - 5 = 16. Vad är x?",
    correctAnswer: "7",
    explanation: "Addera 5 på båda sidor: 3x = 21. Dividera sedan med 3: x = 7.",
  },
  {
    subject: "Svenska", grade: "Åk 9", topic: "Läsförståelse", type: "multiple_choice",
    questionText: "Vilket ord är en synonym till 'generös'?",
    options: ["Givmild", "Snål", "Elak", "Glad"],
    correctAnswer: "Givmild",
    explanation: "Att vara generös innebär att man gärna delar med sig, precis som ordet givmild."
  },
  {
    subject: "Engelska", grade: "Åk 9", topic: "Vocabulary", type: "multiple_choice",
    questionText: "What is the opposite of 'expensive'?",
    options: ["Cheap", "Costly", "Valuable", "Large"],
    correctAnswer: "Cheap",
    explanation: "The opposite of something that costs a lot (expensive) is something that costs very little (cheap)."
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Algebra", type: "multiple_choice",
    questionText: "Förenkla uttrycket: 4a + 2b - a + 3b",
    options: ["3a + 5b", "5a + b", "3a - 5b", "5a + 5b"],
    correctAnswer: "3a + 5b",
    explanation: "Samla a-termer: 4a - a = 3a. Samla b-termer: 2b + 3b = 5b. Resultat: 3a + 5b.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Algebra", type: "numeric",
    questionText: "Beräkna värdet av 2x + y om x = 3 och y = -2",
    correctAnswer: "4",
    explanation: "Sätt in värdena: 2(3) + (-2) = 6 - 2 = 4.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Algebra", type: "numeric",
    questionText: "Lös ekvationen: x/4 + 2 = 6",
    correctAnswer: "16",
    explanation: "Subtrahera 2 på båda sidor: x/4 = 4. Multiplicera med 4: x = 16.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Algebra", type: "multiple_choice",
    questionText: "Vilket uttryck beskriver: 'En siffra minskad med 7, sedan multiplicerad med 2'?",
    options: ["2(x - 7)", "2x - 7", "x - 14", "(x - 7) / 2"],
    correctAnswer: "2(x - 7)",
    explanation: "Siffran minskad med 7 skrivs (x - 7). Sedan multipliceras hela uttrycket med 2: 2(x - 7).",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Algebra", type: "numeric",
    questionText: "Lös ekvationen: 5(y - 2) = 20",
    correctAnswer: "6",
    explanation: "Dividera båda sidor med 5: y - 2 = 4. Addera 2: y = 6.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Algebra", type: "multiple_choice",
    questionText: "Förenkla uttrycket: x * x * x",
    options: ["x^3", "3x", "x+3", "3^x"],
    correctAnswer: "x^3",
    explanation: "Ett tal multiplicerat med sig självt tre gånger skrivs som x upphöjt till 3, alltså x^3.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Algebra", type: "numeric",
    questionText: "Lös ekvationen: 2x = x + 8",
    correctAnswer: "8",
    explanation: "Subtrahera x på båda sidor: 2x - x = 8, vilket ger x = 8.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Algebra", type: "multiple_choice",
    questionText: "Vilket av följande är en linjär ekvation?",
    options: ["y = 3x + 2", "y = x^2", "y = 1/x", "y = 2^x"],
    correctAnswer: "y = 3x + 2",
    explanation: "En linjär ekvation på formen y = kx + m representerar en rät linje.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Algebra", type: "numeric",
    questionText: "Om 3a + 7 = 16, vad är a?",
    correctAnswer: "3",
    explanation: "Subtrahera 7: 3a = 9. Dividera med 3: a = 3.",
  },
  
  // PROCENT
  {
    subject: "Matematik", grade: "Åk 9", topic: "Procent", type: "numeric",
    questionText: "En tröja kostar 400 kr. Priset sänks med 20%. Vad blir det nya priset?",
    correctAnswer: "320",
    explanation: "20% av 400 kr = 0.20 * 400 = 80 kr. Nytt pris = 400 - 80 = 320 kr.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Procent", type: "numeric",
    questionText: "Vad är 15% av 200?",
    correctAnswer: "30",
    explanation: "15% = 0.15. 0.15 * 200 = 30.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Procent", type: "multiple_choice",
    questionText: "Hur skriver man 0.04 i procentform?",
    options: ["4%", "40%", "0.4%", "400%"],
    correctAnswer: "4%",
    explanation: "För att omvandla decimalform till procent multiplicerar man med 100: 0.04 * 100 = 4%.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Procent", type: "numeric",
    questionText: "En vara kostar 500 kr. Priset höjs med 10%, och sänks sedan med 10%. Vad är det nya priset?",
    correctAnswer: "495",
    explanation: "Höjning med 10%: 500 * 1.10 = 550 kr. Sänkning med 10%: 550 * 0.90 = 495 kr.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Procent", type: "multiple_choice",
    questionText: "Kalle hade 50 äpplen och åt upp 10 st. Hur många procent åt han upp?",
    options: ["20%", "10%", "50%", "5%"],
    correctAnswer: "20%",
    explanation: "Delen / Det hela = 10 / 50 = 1/5 = 0.20 = 20%.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Procent", type: "numeric",
    questionText: "Räntan på ett lån är 5%. Hur mycket ränta betalar man på ett år för ett lån på 2000 kr?",
    correctAnswer: "100",
    explanation: "5% av 2000 kr = 0.05 * 2000 = 100 kr.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Procent", type: "multiple_choice",
    questionText: "Vilket av följande motsvarar tre fjärdedelar (3/4)?",
    options: ["75%", "25%", "34%", "133%"],
    correctAnswer: "75%",
    explanation: "3/4 = 0.75 = 75%.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Procent", type: "numeric",
    questionText: "Priset på en mobil sänks från 8000 kr till 6000 kr. Hur stor är sänkningen i procent?",
    correctAnswer: "25",
    explanation: "Sänkning = 2000 kr. 2000 / 8000 = 1/4 = 0.25 = 25%.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Procent", type: "multiple_choice",
    questionText: "Om moms ligger på 25%, vad är momsen för en produkt som kostar 100 kr exklusive moms?",
    options: ["25 kr", "125 kr", "20 kr", "100 kr"],
    correctAnswer: "25 kr",
    explanation: "25% av 100 kr är 0.25 * 100 = 25 kr.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Procent", type: "numeric",
    questionText: "En klass på 30 elever har 18 flickor. Hur många procent är flickor?",
    correctAnswer: "60",
    explanation: "18 / 30 = 6 / 10 = 0.60 = 60%.",
  },

  // GEOMETRI
  {
    subject: "Matematik", grade: "Åk 9", topic: "Geometri", type: "numeric",
    questionText: "Vad är arean av en rektangel med sidorna 5 cm och 8 cm? Svara i cm².",
    correctAnswer: "40",
    explanation: "Arean av en rektangel är längden multiplicerad med bredden: 5 * 8 = 40.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Geometri", type: "numeric",
    questionText: "Vad är omkretsen av en kvadrat med sidan 6 cm? Svara i cm.",
    correctAnswer: "24",
    explanation: "En kvadrat har 4 lika långa sidor: 4 * 6 = 24 cm.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Geometri", type: "multiple_choice",
    questionText: "Vad är summan av vinklarna i en triangel?",
    options: ["180 grader", "360 grader", "90 grader", "270 grader"],
    correctAnswer: "180 grader",
    explanation: "I Euklidisk geometri är vinkelsumman i en triangel alltid exakt 180 grader.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Geometri", type: "numeric",
    questionText: "En rätvinklig triangel har kateterna 3 cm och 4 cm. Vad är längden på hypotenusan? Svara i cm.",
    correctAnswer: "5",
    explanation: "Enligt Pythagoras sats: a² + b² = c². 3² + 4² = 9 + 16 = 25. Roten ur 25 är 5.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Geometri", type: "multiple_choice",
    questionText: "Hur beräknar man arean av en triangel?",
    options: ["(basen * höjden) / 2", "basen * höjden", "sida + sida + sida", "(basen + höjden) / 2"],
    correctAnswer: "(basen * höjden) / 2",
    explanation: "Arean är hälften av basen multiplicerad med höjden.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Geometri", type: "numeric",
    questionText: "Vad är volymen av en kub där varje sida är 3 cm? Svara i cm³.",
    correctAnswer: "27",
    explanation: "Volymen beräknas som sida * sida * sida. 3 * 3 * 3 = 27.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Geometri", type: "numeric",
    questionText: "Cirkelns radie är 5 cm. Omkretsen är ungefär d * pi. Vad är diametern d?",
    correctAnswer: "10",
    explanation: "Diametern är dubbelt så lång som radien: 5 * 2 = 10.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Geometri", type: "multiple_choice",
    questionText: "Vad kallas den längsta sidan i en rätvinklig triangel?",
    options: ["Hypotenusa", "Katet", "Bas", "Radie"],
    correctAnswer: "Hypotenusa",
    explanation: "Den längsta sidan som står mittemot den räta vinkeln kallas hypotenusa.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Geometri", type: "numeric",
    questionText: "Två vinklar i en triangel är 45° och 60°. Hur stor är den tredje vinkeln?",
    correctAnswer: "75",
    explanation: "Vinkelsumman är 180°. 180 - (45 + 60) = 180 - 105 = 75°.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Geometri", type: "multiple_choice",
    questionText: "Vad är formeln för arean av en cirkel?",
    options: ["pi * r²", "2 * pi * r", "pi * d", "r² * h"],
    correctAnswer: "pi * r²",
    explanation: "Arean av en cirkel fås genom att multiplicera pi med radien i kvadrat (r²).",
  },

  // PROBLEMLÖSNING / BLANDAT
  {
    subject: "Matematik", grade: "Åk 9", topic: "Problemlösning", type: "numeric",
    questionText: "Lisa och Kalle delar på 500 kr. Lisa får 100 kr mer än Kalle. Hur mycket får Kalle?",
    correctAnswer: "200",
    explanation: "Låt Kalles andel vara x. Lisa får x + 100. Ekvationen blir: x + x + 100 = 500. 2x = 400. x = 200.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Problemlösning", type: "multiple_choice",
    questionText: "Ett tåg åker 120 km på 1,5 timmar. Vad är dess medelhastighet?",
    options: ["80 km/h", "90 km/h", "100 km/h", "120 km/h"],
    correctAnswer: "80 km/h",
    explanation: "Hastighet = Sträcka / Tid. 120 / 1.5 = 80 km/h.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Problemlösning", type: "numeric",
    questionText: "Om 3 äpplen kostar 15 kr, vad kostar 8 äpplen?",
    correctAnswer: "40",
    explanation: "Ett äpple kostar 15 / 3 = 5 kr. 8 äpplen kostar 8 * 5 = 40 kr.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Problemlösning", type: "numeric",
    questionText: "I en låda finns 4 röda och 6 blå bollar. Hur stor är sannolikheten i procent att dra en röd boll?",
    correctAnswer: "40",
    explanation: "Totalt 10 bollar. Sannolikheten = Gynnsamma / Möjliga = 4 / 10 = 0.4 = 40%.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Problemlösning", type: "multiple_choice",
    questionText: "På en karta i skala 1:10 000 är avståndet mellan två städer 5 cm. Hur långt är det i verkligheten?",
    options: ["500 meter", "50 meter", "5 kilometer", "5 000 meter"],
    correctAnswer: "500 meter",
    explanation: "5 cm * 10 000 = 50 000 cm = 500 meter.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Problemlösning", type: "numeric",
    questionText: "Ett mönster börjar: 2, 5, 8, 11... Vilket är det 10:e talet?",
    correctAnswer: "29",
    explanation: "Skillnaden är 3. Det n:te talet beskrivs av 3n - 1. För n=10: 3(10) - 1 = 29.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Problemlösning", type: "multiple_choice",
    questionText: "Hur många sekunder går det på en timme?",
    options: ["3600", "60", "2400", "7200"],
    correctAnswer: "3600",
    explanation: "Det går 60 sekunder på en minut och 60 minuter på en timme: 60 * 60 = 3600.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Problemlösning", type: "numeric",
    questionText: "En vattenbehållare fylls med 5 liter per minut. Hur många liter fylls på 45 minuter?",
    correctAnswer: "225",
    explanation: "5 liter * 45 minuter = 225 liter.",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Problemlösning", type: "multiple_choice",
    questionText: "Vilket tal saknas i serien: 1, 4, 9, __, 25, 36?",
    options: ["16", "12", "18", "20"],
    correctAnswer: "16",
    explanation: "Detta är serien av kvadrattal: 1², 2², 3², 4²=16, 5², 6².",
  },
  {
    subject: "Matematik", grade: "Åk 9", topic: "Problemlösning", type: "numeric",
    questionText: "Du har 3 byxor och 4 tröjor. Hur många olika kombinationer (outfits) kan du göra?",
    correctAnswer: "12",
    explanation: "Enligt multiplikationsprincipen: 3 byxor * 4 tröjor = 12 kombinationer.",
  },
  // SVENSKA ÅK 9
  {
    subject: "Svenska", grade: "Åk 9", topic: "Läsförståelse", type: "multiple_choice",
    questionText: "Vad betyder ordet 'ambivalent'?",
    options: ["Kluven", "Säker", "Arg", "Snabb"],
    correctAnswer: "Kluven",
    explanation: "Att vara ambivalent innebär att man hyser två motstridiga känslor inför något, man är alltså kluven.",
  },
  {
    subject: "Svenska", grade: "Åk 9", topic: "Grammatik", type: "multiple_choice",
    questionText: "Vilket av följande ord är ett verb?",
    options: ["Springa", "Vacker", "Boll", "Snällt"],
    correctAnswer: "Springa",
    explanation: "Verb är ord som beskriver handlingar eller tillstånd. 'Springa' är en handling.",
  },
  {
    subject: "Svenska", grade: "Åk 9", topic: "Litteratur", type: "multiple_choice",
    questionText: "Vem skrev 'Hemsöborna'?",
    options: ["August Strindberg", "Astrid Lindgren", "Selma Lagerlöf", "Vilhelm Moberg"],
    correctAnswer: "August Strindberg",
    explanation: "Hemsöborna är en av August Strindbergs mest kända romaner, utgiven 1887.",
  },
  {
    subject: "Svenska", grade: "Åk 9", topic: "Språkbruk", type: "multiple_choice",
    questionText: "Vad kallas det när man ger mänskliga egenskaper till döda ting, t.ex. 'väggarna har öron'?",
    options: ["Personifikation", "Liknelse", "Metafor", "Allitteration"],
    correctAnswer: "Personifikation",
    explanation: "Personifikation (eller besjälning) är en stilfigur där ting eller begrepp ges mänskliga egenskaper.",
  },
  {
    subject: "Svenska", grade: "Åk 9", topic: "Läsförståelse", type: "multiple_choice",
    questionText: "Vad är motsatsen till ordet 'generös'?",
    options: ["Girig", "Snäll", "Stor", "Gammal"],
    correctAnswer: "Girig",
    explanation: "Motsatsen till att vara givmild (generös) är att vara självisk och ovillig att dela med sig (girig).",
  },
  // ENGELSKA ÅK 9
  {
    subject: "Engelska", grade: "Åk 9", topic: "Vocabulary", type: "multiple_choice",
    questionText: "What is the English word for 'forskning'?",
    options: ["Research", "Search", "Discovery", "Science"],
    correctAnswer: "Research",
    explanation: "'Research' is the systematic investigation into and study of materials and sources.",
  },
  {
    subject: "Engelska", grade: "Åk 9", topic: "Grammar", type: "multiple_choice",
    questionText: "Choose the correct form: 'She ________ to the store every day.'",
    options: ["goes", "go", "going", "gone"],
    correctAnswer: "goes",
    explanation: "In third person singular (she/he/it) in present simple, we add -s or -es to the verb.",
  },
  {
    subject: "Engelska", grade: "Åk 9", topic: "Reading", type: "multiple_choice",
    questionText: "What does the idiom 'break a leg' mean?",
    options: ["Good luck", "Bad luck", "Get hurt", "Run fast"],
    correctAnswer: "Good luck",
    explanation: "'Break a leg' is a typical English idiom used to wish someone good luck, especially before a performance.",
  },
  {
    subject: "Engelska", grade: "Åk 9", topic: "Grammar", type: "multiple_choice",
    questionText: "Which of these is a synonym for 'happy'?",
    options: ["Joyful", "Sad", "Angry", "Tired"],
    correctAnswer: "Joyful",
    explanation: "'Joyful' means feeling, expressing, or causing great pleasure and happiness.",
  },
  {
    subject: "Engelska", grade: "Åk 9", topic: "Vocabulary", type: "multiple_choice",
    questionText: "What is the past tense of 'see'?",
    options: ["saw", "seen", "seed", "sees"],
    correctAnswer: "saw",
    explanation: "'See' is an irregular verb. Present: see, Past: saw, Past participle: seen.",
  }
];
